import re
import requests
from pathlib import Path

URL = 'https://megaman.miraheze.org/wiki/List_of_Advanced_PET_Battle_Chips'
OUT_DART = Path('lib/core/models/battle_chip_data.dart')

# Helpers to map strings to indices used in BattleChip model
ELEMENT_MAP = {'neutral': 0, 'none': 0, 'fire': 1, 'aqua': 2, 'elec': 3, 'wood': 4}
CATEGORY_MAP = {'attack': 0, 'defense': 1, 'heal': 2, 'support': 3}
RARITY_MAP = {'standard': 0, 'mega': 1, 'giga': 2}

print('Fetching', URL)
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36'}
res = requests.get(URL, timeout=30, headers=headers)
res.raise_for_status()
text = res.text

# Normalize whitespace
norm = text.replace('\r', '')

# We will find table blocks of the pattern: | Chip | NAME ... | ID | 001 | ... | AT | 2 |
pattern = re.compile(r"\|\s*Chip\s*\|\s*([^|\n]+).*?\|\s*ID\s*\|\s*(\d{1,3}).*?\|\s*Type\s*\|\s*([^|\n]+).*?\|\s*Element\s*\|\s*([^|\n]+).*?\|\s*AT\s*\|\s*([^|\n]+)", re.DOTALL | re.IGNORECASE)

matches = pattern.findall(norm)
print('Found', len(matches), 'chip table matches')

chips = {}
for m in matches:
    raw_name, raw_id, raw_type, raw_element, raw_at = m
    name = raw_name.strip().split('|')[-1].strip()
    cid = int(raw_id.strip())
    typ = raw_type.strip().lower()
    element = raw_element.strip().lower()
    at = raw_at.strip()
    # Clean AT - may be N/A or empty
    at_val = None
    try:
        at_val = int(re.search(r"(\d+)", at).group(1))
    except Exception:
        at_val = None

    # Determine category
    cat = 0
    for k in CATEGORY_MAP:
        if k in typ:
            cat = CATEGORY_MAP[k]
            break
    # Element index
    elem_idx = 0
    for k in ELEMENT_MAP:
        if k in element:
            elem_idx = ELEMENT_MAP[k]
            break
    # Rarity
    rar = 0
    # try to guess from nearby text (not reliable); default standard

    chips[cid] = {
        'id': f'chip_{str(cid).zfill(3)}',
        'name': name,
        'damage': at_val if at_val is not None and cat == CATEGORY_MAP['attack'] else 0,
        'description': '',
        'rarityIndex': rar,
        'elementIndex': elem_idx,
        'categoryIndex': cat,
        'code': '?',
    }

# If none found, fallback: generate placeholders 1..320
if not chips:
    for i in range(1, 321):
        chips[i] = {
            'id': f'chip_{str(i).zfill(3)}',
            'name': f'Chip {str(i).zfill(3)}',
            'damage': 0,
            'description': 'Placeholder',
            'rarityIndex': 0,
            'elementIndex': 0,
            'categoryIndex': 0,
            'code': '?',
        }

# Write Dart file
print('Emitting', OUT_DART)
OUT_DART.parent.mkdir(parents=True, exist_ok=True)
with OUT_DART.open('w', encoding='utf-8') as f:
    f.write("// GENERATED by tools/fetch_chip_metadata.py - DO NOT EDIT\n")
    f.write("import 'package:project_pet/core/models/battle_chip.dart';\n\n")
    f.write('final List<BattleChip> generatedFullCatalog = [\n')
    for i in sorted(chips.keys()):
        c = chips[i]
        # escape name and description
        name = c['name'].replace("'", "\\'")
        desc = c['description'].replace("'", "\\'")
        f.write("  BattleChip(\n")
        f.write(f"    id: '{c['id']}',\n")
        f.write(f"    name: '{name}',\n")
        f.write(f"    damage: {c['damage']},\n")
        f.write(f"    description: '{desc}',\n")
        f.write(f"    rarityIndex: {c['rarityIndex']},\n")
        f.write(f"    elementIndex: {c['elementIndex']},\n")
        f.write(f"    categoryIndex: {c['categoryIndex']},\n")
        f.write(f"    code: '{c['code']}',\n")
        f.write("  ),\n")
    f.write('];\n')

print('Wrote', OUT_DART)
print('Done')
