from pathlib import Path
import re

ASSET_DIR = Path('assets/images/chips')
OUT_DART = Path('lib/core/models/battle_chip_data.dart')

files = sorted([p.name for p in ASSET_DIR.glob('BattleChip*.png')] + [p.name for p in ASSET_DIR.glob('BattleChip*.jpg')])
print('Found', len(files), 'chip asset files')

chips = {}
for fn in files:
    m = re.search(r'BattleChip(\d{3})', fn)
    if not m:
        continue
    idx = int(m.group(1))
    cid = idx
    chips[cid] = {
        'id': f'chip_{str(cid).zfill(3)}',
        'name': f'Chip {str(cid).zfill(3)}',
        'damage': 0,
        'description': '',
        'rarityIndex': 0,
        'elementIndex': 0,
        'categoryIndex': 0,
        'code': '?',
        'image': f"assets/images/chips/BattleChip{str(cid).zfill(3)}.png",
    }

# Fallback fill for missing 1..320
for i in range(1, 321):
    if i not in chips:
        chips[i] = {
            'id': f'chip_{str(i).zfill(3)}',
            'name': f'Chip {str(i).zfill(3)}',
            'damage': 0,
            'description': '',
            'rarityIndex': 0,
            'elementIndex': 0,
            'categoryIndex': 0,
            'code': '?',
            'image': None,
        }

OUT_DART.parent.mkdir(parents=True, exist_ok=True)
with OUT_DART.open('w', encoding='utf-8') as f:
    f.write("// GENERATED by tools/generate_chip_data_from_assets.py - DO NOT EDIT\n")
    f.write("import 'package:project_pet/core/models/battle_chip.dart';\n\n")
    f.write('final List<BattleChip> generatedFullCatalog = [\n')
    for i in sorted(chips.keys()):
        c = chips[i]
        name = c['name'].replace("'","\\'")
        desc = c['description'].replace("'","\\'")
        img = c['image']
        f.write('  BattleChip(\n')
        f.write(f"    id: '{c['id']}',\n")
        f.write(f"    name: '{name}',\n")
        f.write(f"    damage: {c['damage']},\n")
        f.write(f"    description: '{desc}',\n")
        f.write(f"    rarityIndex: {c['rarityIndex']},\n")
        f.write(f"    elementIndex: {c['elementIndex']},\n")
        f.write(f"    categoryIndex: {c['categoryIndex']},\n")
        f.write(f"    code: '{c['code']}',\n")
        f.write('  ),\n')
    f.write('];\n')

print('Wrote', OUT_DART)
